MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-C4"
    OUT_CHANNELS: 1024
    USE_STRIDE_UPSAMPLING: True
    USE_DILATION_UPSAMPLING: False
  RPN:
    PRE_NMS_TOP_N_TEST: 12000
    POST_NMS_TOP_N_TEST: 1000
    ANCHOR_SIZES: (15.81, 20.78, 26.07, 31.43, 37.62, 45.27, 53.47,  65.49, 82.68, 110.50, 179.76)
    ANCHOR_STRIDE: (8,)
    ASPECT_RATIOS: (2.44,)
    IGNORE_IGNORE_REGION: True
    PROPOSALS_PAD: 10
    NMS_THRESH: 0.7
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_SCALES : (0.125,)
    USE_VISIBLE_BODY: False
    VISIBLE_RATE_BETA: 5
    METHOD: "roi_head"
    # FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    FEATURE_EXTRACTOR: "ResNet50Conv5ContextROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    CLASSIFICATION_LOSS_BETA: 1
  ROI_HEADS:
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.5
    BG_LOW_IOU_THRESHOLD: 0.0
    SCORE_THRESH: 0.05
    SCALE_INNER_H: 1.8
    SCALE_OUTER_H: 1.8
    SCALE_INNER_W: 1.0
    SCALE_OUTER_W: 1.0
DATASETS:
  TRAIN: ("citypersons_train",)
  TEST: ("citypersons_val",)
SOLVER:
  BASE_LR: 0.008
  WEIGHT_DECAY: 0.0001
  STEPS: (5000, )
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 1000
  VAL_PERIOD: 2000
  START_ATTENTION_ITER: 0
  IMS_PER_BATCH: 8
TEST:
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (1336, )
  MAX_SIZE_TRAIN: 2664
  MIN_SIZE_TEST: 1336
  MAX_SIZE_TEST: 2664
VIS_ACC: False
VIS_IMAGES: False
VIS_PART_AS_RPN_GT: False
GUIDED_NMS: False
START_ATTENTION: True

